# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.0.17
  lark_min: 1.1.7
  cython_version: ">=3.0,<3.1"

package:
  name: lark-cython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lark-cython/lark_cython-${{ version }}.tar.gz
  sha256: a311c4dba35a8bc19f623ec6829ff5421d7ff493ea1a64f591a29fb08d90e884

build:
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cython ${{ cython_version }}
        - python
        - setuptools
  host:
    - cython ${{ cython_version }}
    - pip
    - python
    - setuptools
  run:
    - lark >=${{ lark_min }}
    - python

tests:
  - python:
      imports: lark_cython
  - files:
      source:
        - tests/
    requirements:
      run:
        - lark ${{ lark_min }}.*
        - pytest-cov
    script:
      - coverage run --source=lark_cython --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=100

about:
  summary: A Lark plugin that optimizes LALR parsing using Cython
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lark-parser/lark_cython

extra:
  recipe-maintainers:
    - bollwyvl
